2023-09-27 09:25:49,059 ERROR 3558 [-/127.0.0.1/-/43ms POST /api/report/list] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'bigdata_period.bigdata_period' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:23:39
    at new Promise (<anonymous>)
    at BigDataService.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:11:10)
    at BigDataController.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:8:40)
    sql: select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'bigdata_period.bigdata_period' doesn't exist"
sqlState: "42S02"
index: 0
sql: "select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 3558
hostname: xjswwdeMBP

2023-09-27 09:29:30,346 ERROR 3558 [-/127.0.0.1/-/5ms POST /api/report/list] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'bigdata_period.bigdata_period' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:23:39
    at new Promise (<anonymous>)
    at BigDataService.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:11:10)
    at BigDataController.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:8:40)
    sql: select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'bigdata_period.bigdata_period' doesn't exist"
sqlState: "42S02"
index: 0
sql: "select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 3558
hostname: xjswwdeMBP

2023-09-27 09:43:01,047 ERROR 5732 [-/127.0.0.1/-/31ms POST /api/report/list] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'bigdata_period.bigdata_period' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:23:39
    at new Promise (<anonymous>)
    at BigDataService.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:11:10)
    at BigDataController.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:8:40)
    sql: select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'bigdata_period.bigdata_period' doesn't exist"
sqlState: "42S02"
index: 0
sql: "select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 5732
hostname: xjswwdeMBP

2023-09-27 09:48:34,424 ERROR 5732 [-/127.0.0.1/-/12ms POST /api/report/list] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'bigdata_period.bigdata_period' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:23:39
    at new Promise (<anonymous>)
    at BigDataService.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:11:10)
    at BigDataController.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:8:40)
    sql: select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'bigdata_period.bigdata_period' doesn't exist"
sqlState: "42S02"
index: 0
sql: "select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 5732
hostname: xjswwdeMBP

2023-09-27 09:53:25,156 ERROR 5732 [-/127.0.0.1/-/21ms POST /api/report/list] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'bigdata_period.bigdata_period' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:23:39
    at new Promise (<anonymous>)
    at BigDataService.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:11:10)
    at BigDataController.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:8:40)
    sql: select * from bigdata_period where reportType = 1 order by createTime desc limit 0,10
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'bigdata_period.bigdata_period' doesn't exist"
sqlState: "42S02"
index: 0
sql: "select * from bigdata_period where reportType = 1 order by createTime desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 5732
hostname: xjswwdeMBP

2023-09-27 09:53:25,696 ERROR 5732 [-/127.0.0.1/-/7ms POST /api/report/list] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'bigdata_period.bigdata_period' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:23:39
    at new Promise (<anonymous>)
    at BigDataService.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:11:10)
    at BigDataController.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:8:40)
    sql: select * from bigdata_period where reportType = 2 order by createTime desc limit 0,10
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'bigdata_period.bigdata_period' doesn't exist"
sqlState: "42S02"
index: 0
sql: "select * from bigdata_period where reportType = 2 order by createTime desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 5732
hostname: xjswwdeMBP

2023-09-27 09:58:14,456 ERROR 5732 [-/127.0.0.1/-/4ms POST /api/report/list] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'bigdata_period.bigdata_period' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:23:39
    at new Promise (<anonymous>)
    at BigDataService.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:11:10)
    at BigDataController.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:8:40)
    sql: select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'bigdata_period.bigdata_period' doesn't exist"
sqlState: "42S02"
index: 0
sql: "select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 5732
hostname: xjswwdeMBP

2023-09-27 09:58:14,918 ERROR 5732 [-/127.0.0.1/-/3ms POST /api/report/list] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'bigdata_period.bigdata_period' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:23:39
    at new Promise (<anonymous>)
    at BigDataService.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:11:10)
    at BigDataController.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:8:40)
    sql: select * from bigdata_period where reportType = 4 order by createTime desc limit 0,10
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'bigdata_period.bigdata_period' doesn't exist"
sqlState: "42S02"
index: 0
sql: "select * from bigdata_period where reportType = 4 order by createTime desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 5732
hostname: xjswwdeMBP

2023-09-27 09:58:36,476 ERROR 5732 [-/127.0.0.1/-/3ms POST /api/report/list] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'bigdata_period.bigdata_period' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:23:39
    at new Promise (<anonymous>)
    at BigDataService.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:11:10)
    at BigDataController.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:8:40)
    sql: select * from bigdata_period where reportType = 1 order by createTime desc limit 0,10
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'bigdata_period.bigdata_period' doesn't exist"
sqlState: "42S02"
index: 0
sql: "select * from bigdata_period where reportType = 1 order by createTime desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 5732
hostname: xjswwdeMBP

2023-09-27 09:58:41,653 ERROR 5732 [-/127.0.0.1/-/3ms POST /api/report/list] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'bigdata_period.bigdata_period' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:23:39
    at new Promise (<anonymous>)
    at BigDataService.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:11:10)
    at BigDataController.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:8:40)
    sql: select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'bigdata_period.bigdata_period' doesn't exist"
sqlState: "42S02"
index: 0
sql: "select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 5732
hostname: xjswwdeMBP

2023-09-27 09:58:42,037 ERROR 5732 [-/127.0.0.1/-/3ms POST /api/report/list] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'bigdata_period.bigdata_period' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:23:39
    at new Promise (<anonymous>)
    at BigDataService.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:11:10)
    at BigDataController.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:8:40)
    sql: select * from bigdata_period where reportType = 4 order by createTime desc limit 0,10
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'bigdata_period.bigdata_period' doesn't exist"
sqlState: "42S02"
index: 0
sql: "select * from bigdata_period where reportType = 4 order by createTime desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 5732
hostname: xjswwdeMBP

2023-09-27 10:05:02,464 ERROR 5732 [-/127.0.0.1/-/6ms POST /api/report/list] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'bigdata_period.bigdata_period' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:23:39
    at new Promise (<anonymous>)
    at BigDataService.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:11:10)
    at BigDataController.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:8:40)
    sql: select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'bigdata_period.bigdata_period' doesn't exist"
sqlState: "42S02"
index: 0
sql: "select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 5732
hostname: xjswwdeMBP

2023-09-27 10:20:26,362 ERROR 3549 nodejs.ClusterClientNoResponseError: client no response in 927644ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 3549
hostname: xjswwdeMBP

2023-09-27 11:17:49,324 ERROR 3549 nodejs.ClusterClientNoResponseError: client no response in 82755ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 3549
hostname: xjswwdeMBP

2023-09-27 11:32:22,256 ERROR 3549 nodejs.ClusterClientNoResponseError: client no response in 435718ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 3549
hostname: xjswwdeMBP

2023-09-27 11:49:59,034 ERROR 3549 nodejs.ClusterClientNoResponseError: client no response in 1056684ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 3549
hostname: xjswwdeMBP

2023-09-27 12:03:29,748 ERROR 3549 nodejs.ClusterClientNoResponseError: client no response in 731441ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 3549
hostname: xjswwdeMBP

2023-09-27 12:07:05,642 ERROR 3549 nodejs.ClusterClientNoResponseError: client no response in 215891ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 3549
hostname: xjswwdeMBP

2023-09-27 12:23:12,980 ERROR 3549 nodejs.ClusterClientNoResponseError: client no response in 967249ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 3549
hostname: xjswwdeMBP

2023-09-27 12:39:25,993 ERROR 3549 nodejs.ClusterClientNoResponseError: client no response in 972894ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 3549
hostname: xjswwdeMBP

2023-09-27 12:42:56,944 ERROR 3549 nodejs.ClusterClientNoResponseError: client no response in 210857ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 3549
hostname: xjswwdeMBP

2023-09-27 12:57:31,029 ERROR 3549 nodejs.ClusterClientNoResponseError: client no response in 794059ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 3549
hostname: xjswwdeMBP

2023-09-27 13:16:43,907 ERROR 3549 nodejs.ClusterClientNoResponseError: client no response in 1052762ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 3549
hostname: xjswwdeMBP

2023-09-27 13:30:32,363 ERROR 3549 nodejs.ClusterClientNoResponseError: client no response in 828453ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 3549
hostname: xjswwdeMBP

2023-09-27 14:13:34,112 ERROR 8781 [-/127.0.0.1/-/22ms POST /api/report/createtask] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'taskName' in 'field list'
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at RDSClient.insert (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:159:27)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:106:26
    at new Promise (<anonymous>)
    at BigDataService.createTask (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:104:10)
    sql: INSERT INTO `task_list`(`taskName`, `taskCategory`, `oneTimeExe`, `createTime`) VALUES('55', '一次性', '2023-09-27T14:13:34+08:00', '2023-09-27 14:13:34.107')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'taskName' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `task_list`(`taskName`, `taskCategory`, `oneTimeExe`, `createTime`) VALUES('55', '一次性', '2023-09-27T14:13:34+08:00', '2023-09-27 14:13:34.107')"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 8781
hostname: xjswwdeMBP

2023-09-27 14:38:35,949 ERROR 10147 [-/127.0.0.1/-/3ms POST /api/report/tasklist] nodejs.TypeError: Cannot read properties of undefined (reading 'pageNum')
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:131:14
    at new Promise (<anonymous>)
    at BigDataService.getTaskList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:128:10)
    at BigDataController.getTaskList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:38:40)
    at Object.callFn (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_egg-core@5.3.1@egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_egg-core@5.3.1@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_@eggjs_router@2.0.1@@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_@eggjs_router@2.0.1@@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at next (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_koa-compose@3.2.1@koa-compose/index.js:45:18)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 10147
hostname: xjswwdeMBP

2023-09-27 14:38:59,622 ERROR 10147 [-/127.0.0.1/-/10ms POST /api/report/tasklist] nodejs.TypeError: Cannot read properties of undefined (reading 'pageNum')
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:131:14
    at new Promise (<anonymous>)
    at BigDataService.getTaskList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:128:10)
    at BigDataController.getTaskList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:38:40)
    at Object.callFn (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_egg-core@5.3.1@egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_egg-core@5.3.1@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_@eggjs_router@2.0.1@@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_@eggjs_router@2.0.1@@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at next (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_koa-compose@3.2.1@koa-compose/index.js:45:18)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 10147
hostname: xjswwdeMBP

2023-09-27 14:39:03,591 ERROR 10147 [-/127.0.0.1/-/1ms POST /api/report/tasklist] nodejs.TypeError: Cannot read properties of undefined (reading 'pageNum')
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:131:14
    at new Promise (<anonymous>)
    at BigDataService.getTaskList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:128:10)
    at BigDataController.getTaskList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:38:40)
    at Object.callFn (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_egg-core@5.3.1@egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_egg-core@5.3.1@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_@eggjs_router@2.0.1@@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_@eggjs_router@2.0.1@@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at next (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_koa-compose@3.2.1@koa-compose/index.js:45:18)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 10147
hostname: xjswwdeMBP

2023-09-27 14:55:10,971 ERROR 3549 nodejs.ClusterClientNoResponseError: client no response in 162445ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 3549
hostname: xjswwdeMBP

2023-09-27 14:59:59,763 ERROR 10178 [-/127.0.0.1/-/73ms SCHEDULE /__schedule?path=/Users/xujiashuang/Desktop/bigdata-server/app/schedule/checkTaskStatus.js&cron=0%200%2015%20*%20*%20%3F&type=worker] [Job#1695797999680218736360269581] /Users/xujiashuang/Desktop/bigdata-server/app/schedule/checkTaskStatus.js execute failed, used 66ms. Error: ER_NO_SUCH_TABLE: Table 'bigdata_period.subtask_list' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at RDSClient.select (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:120:27)
    at logTime.subscribe (/Users/xujiashuang/Desktop/bigdata-server/app/schedule/checkTaskStatus.js:40:37)
    at Object.task (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_egg-schedule@4.0.0@egg-schedule/lib/load_schedule.js:37:22)
    at /Users/xujiashuang/Desktop/bigdata-server/node_modules/_egg-schedule@4.0.0@egg-schedule/app.js:48:23
    sql: SELECT * FROM `subtask_list` WHERE `status` = 3 {
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlMessage: "Table 'bigdata_period.subtask_list' doesn't exist",
  sqlState: '42S02',
  index: 0,
  sql: 'SELECT * FROM `subtask_list` WHERE `status` = 3'
}
2023-10-09 14:59:59,925 ERROR 12195 [-/127.0.0.1/-/37ms SCHEDULE /__schedule?path=/Users/xujiashuang/Desktop/bigdata-server/app/schedule/checkTaskStatus.js&cron=0%200%2015%20*%20*%20%3F&type=worker] [Job#16968347998389722141966464581] /Users/xujiashuang/Desktop/bigdata-server/app/schedule/checkTaskStatus.js execute failed, used 33ms. Error: ER_NO_SUCH_TABLE: Table 'bigdata_period.subtask_list' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at RDSClient.select (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:120:27)
    at logTime.subscribe (/Users/xujiashuang/Desktop/bigdata-server/app/schedule/checkTaskStatus.js:40:37)
    at Object.task (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_egg-schedule@4.0.0@egg-schedule/lib/load_schedule.js:37:22)
    at /Users/xujiashuang/Desktop/bigdata-server/node_modules/_egg-schedule@4.0.0@egg-schedule/app.js:48:23
    sql: SELECT * FROM `subtask_list` WHERE `status` = 3 {
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlMessage: "Table 'bigdata_period.subtask_list' doesn't exist",
  sqlState: '42S02',
  index: 0,
  sql: 'SELECT * FROM `subtask_list` WHERE `status` = 3'
}
2023-10-09 15:41:55,504 ERROR 12195 [-/127.0.0.1/-/61ms POST /api/report/createtask] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'reportName' in 'field list'
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at RDSClient.insert (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:159:27)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:110:41
    at new Promise (<anonymous>)
    at BigDataService.createTask (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:108:10)
    sql: INSERT INTO `task_list`(`reportName`, `timeRange`, `periodType`, `priority`, `LargeCategory`, `TimeOn`, `endTime`, `createTime`) VALUES('555', ('2023-10-08T16:00:00.000Z', '2023-11-14T16:00:00.000Z'), 2, '', '周期性', '2023-10-09T00:00:00+08:00', '2023-11-15T00:00:00+08:00', '2023-10-09 15:41:55.455')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'reportName' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `task_list`(`reportName`, `timeRange`, `periodType`, `priority`, `LargeCategory`, `TimeOn`, `endTime`, `createTime`) VALUES('555', ('2023-10-08T16:00:00.000Z', '2023-11-14T16:00:00.000Z'), 2, '', '周期性', '2023-10-09T00:00:00+08:00', '2023-11-15T00:00:00+08:00', '2023-10-09 15:41:55.455')"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 12195
hostname: xjswwdeMBP

2023-10-09 15:46:51,143 ERROR 12195 [-/127.0.0.1/-/56ms POST /api/report/createtask] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'reportName' in 'field list'
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at RDSClient.insert (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:159:27)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:110:41
    at new Promise (<anonymous>)
    at BigDataService.createTask (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:108:10)
    sql: INSERT INTO `task_list`(`reportName`, `timeRange`, `periodType`, `priority`, `LargeCategory`, `TimeOn`, `endTime`, `createTime`) VALUES('555', ('2023-10-08T16:00:00.000Z', '2023-11-14T16:00:00.000Z'), 2, '', '周期性', '2023-10-09T00:00:00+08:00', '2023-11-15T00:00:00+08:00', '2023-10-09 15:46:51.100')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'reportName' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `task_list`(`reportName`, `timeRange`, `periodType`, `priority`, `LargeCategory`, `TimeOn`, `endTime`, `createTime`) VALUES('555', ('2023-10-08T16:00:00.000Z', '2023-11-14T16:00:00.000Z'), 2, '', '周期性', '2023-10-09T00:00:00+08:00', '2023-11-15T00:00:00+08:00', '2023-10-09 15:46:51.100')"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 12195
hostname: xjswwdeMBP

2023-10-09 15:47:24,657 ERROR 12195 [-/127.0.0.1/-/8ms POST /api/report/createtask] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'reportName' in 'field list'
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at RDSClient.insert (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:159:27)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:110:41
    at new Promise (<anonymous>)
    at BigDataService.createTask (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:108:10)
    sql: INSERT INTO `task_list`(`reportName`, `timeRange`, `periodType`, `priority`, `LargeCategory`, `TimeOn`, `endTime`, `createTime`) VALUES('555', ('2023-10-08T16:00:00.000Z', '2023-11-14T16:00:00.000Z'), 2, '', '周期性', '2023-10-09T00:00:00+08:00', '2023-11-15T00:00:00+08:00', '2023-10-09 15:47:24.652')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'reportName' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `task_list`(`reportName`, `timeRange`, `periodType`, `priority`, `LargeCategory`, `TimeOn`, `endTime`, `createTime`) VALUES('555', ('2023-10-08T16:00:00.000Z', '2023-11-14T16:00:00.000Z'), 2, '', '周期性', '2023-10-09T00:00:00+08:00', '2023-11-15T00:00:00+08:00', '2023-10-09 15:47:24.652')"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 12195
hostname: xjswwdeMBP

2023-10-09 15:47:51,718 ERROR 12195 [-/127.0.0.1/-/6ms POST /api/report/createtask] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'reportName' in 'field list'
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at RDSClient.insert (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:159:27)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:110:41
    at new Promise (<anonymous>)
    at BigDataService.createTask (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:108:10)
    sql: INSERT INTO `task_list`(`reportName`, `timeRange`, `periodType`, `priority`, `LargeCategory`, `TimeOn`, `endTime`, `createTime`) VALUES('555', ('2023-10-08T16:00:00.000Z', '2023-11-14T16:00:00.000Z'), 2, '', '周期性', '2023-10-09T00:00:00+08:00', '2023-11-15T00:00:00+08:00', '2023-10-09 15:47:51.713')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'reportName' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `task_list`(`reportName`, `timeRange`, `periodType`, `priority`, `LargeCategory`, `TimeOn`, `endTime`, `createTime`) VALUES('555', ('2023-10-08T16:00:00.000Z', '2023-11-14T16:00:00.000Z'), 2, '', '周期性', '2023-10-09T00:00:00+08:00', '2023-11-15T00:00:00+08:00', '2023-10-09 15:47:51.713')"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 12195
hostname: xjswwdeMBP

2023-10-09 16:05:37,637 ERROR 18896 [-/127.0.0.1/-/42ms POST /api/report/createtask] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'bigdata_period.task_list' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at RDSClient.insert (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:159:27)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:110:41
    at new Promise (<anonymous>)
    at BigDataService.createTask (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:108:10)
    sql: INSERT INTO `task_list`(`reportName`, `timeRange`, `periodType`, `priority`, `LargeCategory`, `TimeOn`, `endTime`, `createTime`) VALUES('ceshi', ('2023-10-08T16:00:00.000Z', '2024-01-08T16:00:00.000Z'), 1, '', '周期性', '2023-10-09T00:00:00+08:00', '2024-01-09T00:00:00+08:00', '2023-10-09 16:05:37.610')
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'bigdata_period.task_list' doesn't exist"
sqlState: "42S02"
index: 0
sql: "INSERT INTO `task_list`(`reportName`, `timeRange`, `periodType`, `priority`, `LargeCategory`, `TimeOn`, `endTime`, `createTime`) VALUES('ceshi', ('2023-10-08T16:00:00.000Z', '2024-01-08T16:00:00.000Z'), 1, '', '周期性', '2023-10-09T00:00:00+08:00', '2024-01-09T00:00:00+08:00', '2023-10-09 16:05:37.610')"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 18896
hostname: xjswwdeMBP

2023-10-09 16:07:12,212 ERROR 18924 [-/127.0.0.1/-/34ms POST /api/report/createtask] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'timeRange' in 'field list'
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at RDSClient.insert (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:159:27)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:110:41
    at new Promise (<anonymous>)
    at BigDataService.createTask (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:108:10)
    sql: INSERT INTO `report_list`(`reportName`, `timeRange`, `periodType`, `priority`, `LargeCategory`, `TimeOn`, `endTime`, `createTime`) VALUES('ceshi', ('2023-10-08T16:00:00.000Z', '2024-01-08T16:00:00.000Z'), 1, '', '周期性', '2023-10-09T00:00:00+08:00', '2024-01-09T00:00:00+08:00', '2023-10-09 16:07:12.188')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'timeRange' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `report_list`(`reportName`, `timeRange`, `periodType`, `priority`, `LargeCategory`, `TimeOn`, `endTime`, `createTime`) VALUES('ceshi', ('2023-10-08T16:00:00.000Z', '2024-01-08T16:00:00.000Z'), 1, '', '周期性', '2023-10-09T00:00:00+08:00', '2024-01-09T00:00:00+08:00', '2023-10-09 16:07:12.188')"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 18924
hostname: xjswwdeMBP

2023-10-09 16:20:25,707 ERROR 18997 [-/127.0.0.1/-/49ms POST /api/report/addtasktype] nodejs.ER_NO_DEFAULT_FOR_FIELDError: ER_NO_DEFAULT_FOR_FIELD: Field 'reportTypeName' doesn't have a default value
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at RDSClient.insert (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:159:27)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:151:41
    at new Promise (<anonymous>)
    at BigDataService.createTaskType (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:149:10)
    sql: INSERT INTO `report_Type`(`modeName`, `createTime`) VALUES('', '2023-10-09 16:20:25.661')
code: "ER_NO_DEFAULT_FOR_FIELD"
errno: 1364
sqlMessage: "Field 'reportTypeName' doesn't have a default value"
sqlState: "HY000"
index: 0
sql: "INSERT INTO `report_Type`(`modeName`, `createTime`) VALUES('', '2023-10-09 16:20:25.661')"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_DEFAULT_FOR_FIELDError"
pid: 18997
hostname: xjswwdeMBP

2023-10-09 16:57:53,583 ERROR 18997 [-/127.0.0.1/-/59ms POST /api/report/tasklist] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'bigdata_period.task_list' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:134:39
    at new Promise (<anonymous>)
    at BigDataService.getTaskList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:128:10)
    at BigDataController.getTaskList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:38:40)
    sql: select * from task_list order by createTime desc limit 0,10
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'bigdata_period.task_list' doesn't exist"
sqlState: "42S02"
index: 0
sql: "select * from task_list order by createTime desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 18997
hostname: xjswwdeMBP

2023-10-09 17:18:40,388 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 975159ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 17:33:55,334 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 914849ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 17:49:22,424 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 927084ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 18:06:35,534 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 1033072ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 18:22:37,808 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 962265ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 18:39:54,403 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 1036543ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 18:55:21,402 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 926908ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 19:03:25,594 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 484112ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 19:12:58,430 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 572831ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 19:27:01,182 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 746744ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 19:35:36,712 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 515527ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 19:51:34,704 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 957983ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 20:06:48,639 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 913929ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 20:23:52,637 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 1023992ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 20:39:18,619 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 925977ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 20:56:28,536 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 1029913ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 21:09:51,188 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 802648ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 21:13:16,389 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 205104ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 21:21:08,735 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 472340ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 21:23:08,439 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 84356ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 21:26:21,814 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 158837ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 21:28:25,083 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 123245ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 21:43:56,611 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 931521ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 21:59:08,590 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 911951ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 22:14:40,540 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 931943ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 23:20:28,466 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 1032001ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 23:36:31,145 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 962673ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-09 23:52:21,896 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 950749ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

2023-10-10 00:08:00,074 ERROR 12187 nodejs.ClusterClientNoResponseError: client no response in 938045ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_cluster-client@3.5.0@cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 12187
hostname: xjswwdeMBP

